"""Render the spike report from ``analysis.json``; nothing in it is typed by hand."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

from hyperdime.spike.manifest import read_json, require_complete


def write_report(root: Path, output: Path) -> Path:
    manifest = require_complete(root / "analysis")
    analysis = read_json(root / "analysis" / "analysis.json")
    output.mkdir(parents=True, exist_ok=True)
    path = output / "README.md"
    path.write_text(render(analysis, manifest), encoding="utf-8")
    return path


def render(analysis: Mapping[str, Any], manifest: Mapping[str, Any]) -> str:
    config, summary = analysis["config"], analysis["summary"]
    mask, criteria = analysis["mask"], analysis["criteria"]
    envs: list[str] = config["envs"]
    k = str(config["headline_k"])

    def ndcg(env: str, system: str, budget: str = k) -> float:
        value: float = summary[env][system][budget]["ndcg@10"]
        return value

    dirty = " (dirty tree)" if manifest["git_dirty"] else ""
    significant_headroom = ", ".join(criteria["headroom_significant"]) or "none"
    lines = [
        "# F0 spike: selector shift (H1)",
        "",
        "Generated by `python -m hyperdime.spike report` from",
        "`artifacts/spike/analysis/analysis.json`. Exploratory results: they decide whether to",
        "build the roadmap and are not paper numbers.",
        "",
        f"- Code: `{manifest['git_commit']}`{dirty}",
        f"- Seeds: {config['seeds']}; budget k = {k} of 1024 (30%); nDCG@10 with exact scoring",
        f"- Mask analysis battery: {config['battery_size']} evaluation queries, labels unused",
        "",
        f"## Verdict: H1 {criteria['verdict']}",
        "",
        _row("Criterion (research R0)", "Result", "Met"),
        _rule(3),
        _row(
            "C1 transferred selectors lose to in-domain on ≥ half of the pairs",
            f"{len(criteria['transfer_significant'])}/{len(criteria['transfer'])} significant",
            _yes(criteria["c1_transfer_loss"]),
        ),
        _row(
            "C2 masks differ more across environments than across seeds",
            f"overlap@k {mask['overlap_cross_seed']:.3f} (seeds) vs "
            f"{mask['overlap_cross_env']:.3f} (envs), p = {mask['overlap_p']:.4f}",
            _yes(criteria["c2_masks_shift"]),
        ),
        _row(
            "C3 per-domain beats the global selector on ≥ 2 environments",
            f"{len(criteria['headroom_significant'])}/{len(envs)} ({significant_headroom})",
            _yes(criteria["c3_headroom_over_global"]),
        ),
        "",
        "## Main results (nDCG@10)",
        "",
        _row(
            "Environment",
            "Eval queries",
            "Full 1024",
            "Prefix",
            "Random",
            "Global",
            "In-domain",
            "Mean transferred",
            "Oracle",
        ),
        _rule(9),
    ]
    for env in envs:
        transferred = [ndcg(env, f"selector:{src}") for src in envs if src != env]
        lines.append(
            _row(
                env,
                str(config["counts"][env]["evaluation"]),
                f"{ndcg(env, 'full', '1024'):.4f}",
                *(f"{ndcg(env, name):.4f}" for name in ("prefix", "random", "global")),
                f"{ndcg(env, f'selector:{env}'):.4f}",
                f"{sum(transferred) / len(transferred):.4f}",
                f"{ndcg(env, 'oracle'):.4f}",
            )
        )
    lines += [
        "",
        f"## Transfer matrix (nDCG@10 at k = {k}; rows train, columns test)",
        "",
        "`*` = significantly below the in-domain selector (paired randomization test,",
        "Holm-adjusted, α = 0.05).",
        "",
        _row("train \\ test", *envs),
        _rule(len(envs) + 1),
    ]
    for src in envs:
        cells = []
        for dst in envs:
            value = f"{ndcg(dst, f'selector:{src}'):.4f}"
            if src == dst:
                value = f"**{value}**"
            elif f"{src}->{dst}" in criteria["transfer_significant"]:
                value += "*"
            cells.append(value)
        lines.append(_row(src, *cells))
    lines += [
        "",
        "## Headroom: in-domain minus global selector",
        "",
        _row("Environment", "Δ nDCG@10", "95% CI", "p (Holm)"),
        _rule(4),
    ]
    for env in envs:
        h = criteria["headroom"][env]
        ci = f"[{h['ci'][0]:+.4f}, {h['ci'][1]:+.4f}]"
        lines.append(_row(env, f"{h['diff']:+.4f}", ci, f"{h['p_holm']:.4f}"))
    lines += [
        "",
        "## Mask behavior",
        "",
        f"Mean overlap@{k}: {mask['overlap_cross_seed']:.4f} between seeds of one environment, "
        f"{mask['overlap_cross_env']:.4f} between environments; difference CI "
        f"[{mask['overlap_diff_ci'][0]:+.4f}, {mask['overlap_diff_ci'][1]:+.4f}].",
        "",
        "Jensen-Shannon divergence of mean importance (diagonal: mean across seeds):",
        "",
        *_matrix(envs, mask["js_env"], mask["js_seed"], "{:.4f}"),
        "",
        "Spearman correlation of mean importance (diagonal: mean across seeds):",
        "",
        *_matrix(envs, mask["spearman_env"], mask["spearman_seed"], "{:.3f}"),
        "",
        "## Budget sweep (nDCG@10)",
        "",
        _row("Environment", "System", *(f"k={kv}" for kv in config["k_values"])),
        _rule(len(config["k_values"]) + 2),
    ]
    for env in envs:
        for name in ("prefix", "global", f"selector:{env}", "oracle"):
            label = "in-domain" if name == f"selector:{env}" else name
            values = [f"{ndcg(env, name, str(kv)):.4f}" for kv in config["k_values"]]
            lines.append(_row(env, label, *values))
    lines += [
        "",
        "## Setup",
        "",
        _row("Environment", "Train", "Validation", "Eval", "Temperature (validation nDCG@10)"),
        _rule(5),
    ]
    for env in envs:
        counts, temp = config["counts"][env], config["temperatures"][env]
        scores = ", ".join(f"{t}: {s:.4f}" for t, s in temp["validation_ndcg@10"].items())
        lines.append(
            _row(
                env,
                str(counts["train"]),
                str(counts["validation"]),
                str(counts["evaluation"]),
                f"{temp['temperature']} ({scores})",
            )
        )
    return "\n".join(lines) + "\n"


def _row(*cells: str) -> str:
    return "| " + " | ".join(cells) + " |"


def _rule(columns: int) -> str:
    return "|" + "---|" * columns


def _matrix(
    envs: Sequence[str],
    values: Mapping[str, Mapping[str, float]],
    diagonal: Mapping[str, float],
    fmt: str,
) -> list[str]:
    rows = [_row("", *envs), _rule(len(envs) + 1)]
    for x in envs:
        cells = [fmt.format(diagonal[x] if x == y else values[x][y]) for y in envs]
        rows.append(_row(x, *cells))
    return rows


def _yes(flag: bool) -> str:
    return "yes" if flag else "no"
